// src/types/moderation.ts
export enum ModerationType {
    ARTICLE_FLAG = 'ARTICLE_FLAG',
    COMMENT_FLAG = 'COMMENT_FLAG',
    USER_REPORT = 'USER_REPORT',
    PLANT_VERIFICATION = 'PLANT_VERIFICATION',
    CONTENT_CHANGE = 'CONTENT_CHANGE',
    USER_BAN = 'USER_BAN',
    CARE_TIP_FLAG = 'CARE_TIP_FLAG'
  }
  
